/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductResponse {
  categorieId?: number;
  categorieName?: string;
  description?: string;
  id?: number;
  name?: string;
  price?: number;
  quantity?: number;
}
