/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductRequest {
  categorieId: number;
  description: string;
  id?: number;
  name: string;
  price: number;
  quantity: number;
}
