/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CategoryRequest } from './models/category-request';
export type { CategoryResponse } from './models/category-response';
export type { ProductRequest } from './models/product-request';
export type { ProductResponse } from './models/product-response';
