/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ProductsService } from './services/products.service';
export { CategoriesService } from './services/categories.service';
